### PR TITLE
Two column view

### PR DESCRIPTION
**Pull request by rsbohn**
Declarations on the left, results on the right.
Otherwise I have to scroll back and forth to view the output.

### CODE REVIEW

**Comment by windley** [comment]
Randall, this looks like this when I put it in my dev box. Is that what you were intending? 

screenshot 2016-02-10 15 03 21

**Comment by rsbohn** [comment]
No, the intent was to have the declarations on the  left and the results on
the right.
Sorry I wasn't able to test it better before I submitted it.

**Comment by rsbohn** [comment]
The ramdajs repl does a good job: http://ramdajs.com/repl/

**Comment by windley** [comment]
Found the problem. You just hadn’t included the editor (which is an empty div until the JS get ahold of it in the left hand side (the textarea isn’t the editor, it’s where the JS copies the editor content before submitting). 

Thanks for the update.

**Comment by rsbohn** [comment]
Cool, thanks!

**Pull request merged**
